name: Waka Readme

on:
  schedule:
    # Roda todo dia Ã s 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LINES_OF_CODE: "True
          
      # - uses: athul/waka-readme@master
      #   with:
      #     WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      #     SHOW_TITLE: true
      #     SECTION_NAME: ðŸš€ Minha Atividade de Coding
      #     BLOCKS: â£€â£„â£¤â£¦â£¶â£·â£¿
      #     TIME_RANGE: last_7_days
      #     SHOW_TIME: true
      #     SHOW_TOTAL: true
      #     SHOW_MASKED_TIME: true
      #     SHOW_COMMIT: true
      #     SHOW_DAYS_OF_WEEK: true
      #     SHOW_LANGUAGE: true
      #     SHOW_EDITORS: true
      #     SHOW_OS: true
      #     LANG_COUNT: 10
